<x-layouts.app>
<a href="{{ route('admin.cms.impact') }}">← Notre impact</a><h1 class="h3 my-3">{{ $indicator->exists ? 'Modifier un indicateur' : 'Ajouter un indicateur' }}</h1>
@include('cms.work.feedback')
<form method="post" action="{{ $indicator->exists ? route('admin.cms.impact.update', $indicator) : route('admin.cms.impact.store') }}" class="card card-body">@csrf
@if($indicator->exists) @method('PUT')<input type="hidden" name="revision" value="{{ old('revision', \App\Http\Controllers\CmsImpactController::revision($indicator)) }}">@endif
<label for="title" class="form-label">Libellé de l’indicateur</label><input id="title" name="title" class="form-control mb-3" maxlength="255" value="{{ old('title', $indicator->title) }}" required>
<label for="description" class="form-label">Description</label><textarea id="description" name="description" class="form-control mb-3" maxlength="2000" rows="3">{{ old('description', $indicator->description) }}</textarea>
<label for="unit" class="form-label">Unité</label>@if($indicator->exists)<input type="hidden" name="unit" value="{{ $indicator->unit }}"><p>{{ $indicator->unit === 'percent' ? 'Pourcentage' : 'Nombre' }}</p>@else<select id="unit" name="unit" class="form-select mb-3"><option value="count" @selected(old('unit') !== 'percent')>Nombre</option><option value="percent" @selected(old('unit') === 'percent')>Pourcentage</option></select>@endif
<label for="is_visible" class="form-label">Affichage</label><select id="is_visible" name="is_visible" class="form-select mb-3"><option value="1" @selected(old('is_visible', $indicator->is_visible))>Visible</option><option value="0" @selected(!old('is_visible', $indicator->is_visible))>Masqué</option></select>
<label for="sort_order" class="form-label">Ordre d’affichage</label><input id="sort_order" name="sort_order" class="form-control mb-4" type="number" min="0" max="100000" value="{{ old('sort_order', $indicator->sort_order) }}" required>
<h2 class="h5">{{ $indicator->exists ? 'Ajouter un nouveau relevé' : 'Premier relevé' }}</h2>@if($indicator->exists)<p>Laissez la valeur vide pour modifier uniquement la présentation. Un nouveau relevé actualise aussi les autres sections utilisant cet indicateur.</p>@endif
<label for="value" class="form-label">Valeur</label><input id="value" name="value" class="form-control mb-3" type="number" min="0" step="0.0001" value="{{ old('value') }}" @required(!$indicator->exists)>
<label for="period_label" class="form-label">Période de référence</label><input id="period_label" name="period_label" class="form-control mb-3" maxlength="255" value="{{ old('period_label') }}" placeholder="Ex. Année 2026">
<label for="source" class="form-label">Source du relevé (conservée dans l’administration)</label><input id="source" name="source" class="form-control mb-3" maxlength="2000" value="{{ old('source') }}" @required(!$indicator->exists)>
<label for="change_note" class="form-label">Note de mise à jour</label><textarea id="change_note" name="change_note" class="form-control mb-3" maxlength="2000">{{ old('change_note') }}</textarea><button class="btn btn-primary align-self-start">Enregistrer</button></form>
@if($history)<h2 class="h4 mt-4">Historique des relevés</h2><div class="table-responsive"><table class="table"><thead><tr><th>Valeur</th><th>Période</th><th>Source</th><th>Note</th><th>Enregistré le</th></tr></thead><tbody>@forelse($history as $value)<tr><td>{{ $value->value }}{{ $indicator->unit === 'percent' ? ' %' : '' }}</td><td>{{ $value->period_label }}</td><td>{{ $value->source }}</td><td>{{ $value->change_note }}</td><td>{{ $value->created_at->format('d/m/Y H:i') }}</td></tr>@empty<tr><td colspan="5">Aucun relevé.</td></tr>@endforelse</tbody></table></div>@if($history->hasPages())<nav class="d-flex gap-3" aria-label="Historique">@if($history->previousPageUrl())<a href="{{ $history->previousPageUrl() }}">← Précédent</a>@endif<span>Page {{ $history->currentPage() }} sur {{ $history->lastPage() }}</span>@if($history->nextPageUrl())<a href="{{ $history->nextPageUrl() }}">Suivant →</a>@endif</nav>@endif @endif
</x-layouts.app>
