<x-layouts.app>
<div class="d-flex justify-content-between flex-wrap gap-3 mb-4"><div><h1 class="h3">Notre impact — indicateurs</h1><p>Ajoutez vos indicateurs et actualisez leurs valeurs. Chaque relevé reste conservé dans l’historique.</p></div><a class="btn btn-outline-primary align-self-start" href="{{ route('impact') }}">Voir la page publique</a></div>
@include('cms.work.feedback')
<a href="{{ route('admin.cms.impact.create') }}" class="btn btn-primary mb-3">Ajouter un indicateur</a>
<p>Les indicateurs visibles disposant d’un relevé apparaissent dans les cartes, selon leur ordre d’affichage.</p>
<div class="card table-responsive mb-4"><table class="table align-middle"><thead><tr><th>Indicateur</th><th>Dernière valeur</th><th>Période</th><th>Affichage</th><th>Action</th></tr></thead><tbody>@forelse($indicators as $indicator)<tr><th>{{ $indicator->title }}</th><td>{{ $indicator->currentValue ? rtrim(rtrim(number_format((float)$indicator->currentValue->value, 4, ',', ' '), '0'), ',').($indicator->unit === 'percent' ? ' %' : '') : 'Sans relevé' }}</td><td>{{ $indicator->currentValue?->period_label ?? '—' }}</td><td>{{ $indicator->is_visible ? 'Visible' : 'Masqué' }}</td><td><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.cms.impact.edit', $indicator) }}">Modifier / actualiser</a></td></tr>@empty<tr><td colspan="5">Aucun indicateur.</td></tr>@endforelse</tbody></table></div>
@if($page)<a class="btn btn-outline-primary mb-3" href="{{ route('admin.cms.titles.edit', $page) }}">Personnaliser l’en-tête et « Au-delà des chiffres »</a>@endif
<form method="post" action="{{ route('admin.cms.impact.presentation') }}" class="card card-body">@csrf @method('PUT')<label for="introduction" class="form-label">Introduction de la page</label><textarea id="introduction" name="introduction" class="form-control mb-3" rows="3" maxlength="1000" required>{{ old('introduction', $introduction ?? 'Découvrez les résultats des actions de l’ADPDH à travers nos indicateurs, actualisés au fil de nos interventions.') }}</textarea><button class="btn btn-primary align-self-start">Enregistrer l’introduction</button></form>
</x-layouts.app>
