<x-layouts.app>
<div class="d-flex justify-content-between flex-wrap gap-3 mb-4"><div><h1 class="h3">Nos succès</h1><p>Seuls les témoignages visibles et non fictifs sont affichés, sans lien vers une fiche de détail.</p></div><a href="{{ route('success') }}" class="btn btn-outline-primary align-self-start">Voir la page publique</a></div>
@include('cms.work.feedback')
@if($section)
<div class="card card-body mb-4"><div class="d-flex justify-content-between flex-wrap gap-3 mb-3"><h2 class="h5">Témoignages</h2><a class="btn btn-primary" href="{{ route('admin.cms.sections.create', $section) }}">Ajouter un témoignage</a></div><p>Ces témoignages sont partagés avec la section de l’accueil. La visibilité se règle dans chaque fiche.</p><div class="table-responsive"><table class="table"><thead><tr><th>Témoignage</th><th>Affichage</th><th>Action</th></tr></thead><tbody>@forelse($section->contents as $item)<tr><th>{{ $item->title }}</th><td>{{ $item->is_visible && !$item->is_demo ? 'Visible' : 'Masqué' }}</td><td><a class="btn btn-outline-primary btn-sm" href="{{ route('admin.cms.sections.content.edit', [$section, $item]) }}">Modifier / visibilité</a></td></tr>@empty<tr><td colspan="3">Aucun témoignage pour le moment.</td></tr>@endforelse</tbody></table></div></div>
@endif
@if($page)<a class="btn btn-outline-primary mb-4" href="{{ route('admin.cms.titles.edit', $page) }}">Personnaliser les titres de la page</a>@endif
<form method="post" action="{{ route('admin.cms.success.save') }}" class="card card-body">@csrf @method('PUT')
<h2 class="h5">Présentation de la page</h2><label for="introduction" class="form-label">Introduction</label><textarea name="introduction" id="introduction" class="form-control mb-4" rows="3" maxlength="1000" required>{{ old('introduction', $settings['adpdh.success.introduction'] ?? 'Les récits donnent une place aux expériences individuelles, aux changements du quotidien et aux perspectives des personnes accompagnées.') }}</textarea>
<h2 class="h5">Nos pages sur les réseaux sociaux</h2><p>Renseignez vos adresses puis activez les réseaux à afficher. Un réseau désactivé reste masqué même si son adresse est enregistrée.</p>
@foreach($networks as $key => $label)<div class="border rounded p-3 mb-3"><input type="hidden" name="social[{{ $key }}][enabled]" value="0"><div class="form-check form-switch mb-2"><input class="form-check-input" type="checkbox" role="switch" id="social-{{ $key }}" name="social[{{ $key }}][enabled]" value="1" @checked(old('social.'.$key.'.enabled', $settings['adpdh.success.social.'.$key.'.enabled'] ?? false))><label class="form-check-label" for="social-{{ $key }}">Afficher {{ $label }}</label></div><label for="url-{{ $key }}" class="form-label">Adresse de notre page {{ $label }}</label><input type="url" class="form-control" id="url-{{ $key }}" name="social[{{ $key }}][url]" maxlength="1000" placeholder="https://…" value="{{ old('social.'.$key.'.url', $settings['adpdh.success.social.'.$key.'.url'] ?? '') }}"></div>@endforeach
<button class="btn btn-primary align-self-start">Enregistrer</button></form>
</x-layouts.app>
