<?php
namespace ADPDH\Theme;
defined('ABSPATH') || exit;
// Ported from current Laravel view: donation.blade.php.
?>

<div class="container breadcrumb" aria-label="Fil d’Ariane"><a href="<?php echo e(route('home')); ?>"><?php echo e(copy_text('donation', 'text_a8ff8fd207', 'Accueil')); ?></a><span aria-hidden="true">/</span><span><?php echo e($copy['page_title']); ?></span></div><section class="container about-heading"><p class="eyebrow"><?php echo e($copy['eyebrow']); ?></p><h1><?php echo e($copy['heading']); ?><br><em><?php echo e($copy['heading_accent']); ?></em></h1><p><?php echo e($copy['introduction']); ?></p></section>
<section class="container donation-layout"><div><figure class="editorial-photo"><img src="<?php echo e(page_image('workshop-1200.webp')); ?>" width="1680" height="1260" alt="Illustration : des entrepreneures dans un atelier de couture" loading="lazy"><figcaption>Image d’illustration générée par IA</figcaption></figure><div class="donation-purpose"><h2><?php echo e($copy['purpose_title']); ?></h2><p><?php echo e($copy['purpose_text']); ?></p><a class="text-link" href="<?php echo e(route('activities')); ?>"><?php echo e($copy['activities_label']); ?></a></div></div><aside class="support-panel"><p class="eyebrow"><?php echo e($copy['bank_eyebrow']); ?></p><h2><?php echo e($copy['bank_title']); ?></h2><p><?php echo e($copy['bank_intro']); ?></p><dl class="bank-details"><div><dt><?php echo e($copy['bank_label']); ?></dt><dd><?php echo e($copy['bank']); ?></dd></div><div><dt><?php echo e($copy['account_name_label']); ?></dt><dd><?php echo e($copy['account_name']); ?></dd></div><div><dt><?php echo e($copy['account_number_label']); ?></dt><dd class="bank-account"><?php echo e($copy['account_number']); ?></dd></div></dl><p><?php echo e($copy['contact_text']); ?></p><a class="button button-green" href="mailto:<?php echo e($copy['email']); ?>?subject=<?php echo e(rawurlencode($copy['email_subject'])); ?>"><?php echo e($copy['contact_label']); ?></a><p><a href="tel:<?php echo e(preg_replace('/[^+0-9]/', '', $copy['phone'])); ?>"><?php echo e($copy['phone']); ?></a></p><p class="source-note"><?php echo e($copy['notice']); ?></p></aside></section>
<section class="section container"><p class="eyebrow"><?php echo e($copy['faq_title']); ?></p><div class="support-faq"><details><summary><?php echo e($copy['question_1']); ?></summary><p><?php echo e($copy['answer_1']); ?></p></details><details><summary><?php echo e($copy['question_2']); ?></summary><p><?php echo e($copy['answer_2']); ?></p><a class="text-link" href="<?php echo e(route('partnership')); ?>"><?php echo e($copy['partnership_label']); ?></a></details><details><summary><?php echo e($copy['question_3']); ?></summary><p><?php echo e($copy['answer_3']); ?></p><a class="text-link" href="<?php echo e(route('impact')); ?>"><?php echo e($copy['impact_label']); ?></a></details></div></section>


