<?php
namespace ADPDH\Theme;
defined('ABSPATH') || exit;
// Ported from current Laravel view: resources.blade.php.
?>

<div class="resource-page">
<nav class="container breadcrumb" aria-label="Fil d’Ariane"><a href="<?php echo e(route('home')); ?>"><?php echo e(copy_text('resources', 'text_a8ff8fd207', 'Accueil')); ?></a><span aria-hidden="true">/</span><span aria-current="page"><?php echo e(copy_text('resources', 'text_926ac9d127', 'Ressources')); ?></span></nav>
<section class="container about-heading"><p class="eyebrow"><?php echo e(copy_text('resources', 'text_f1f4b8bc43', 'Ressources et publications')); ?></p><h1><?php echo e(copy_text('resources', 'text_5672f51ddb', 'Comprendre notre action.')); ?><br><em><?php echo e(copy_text('resources', 'text_00fefebc74', 'Partager les savoirs.')); ?></em></h1><p><?php echo e(copy_text('resources', 'text_3463519697', 'Consultez nos documents de référence, rapports et supports de formation directement sur le site.')); ?></p></section>
<section class="container activity-list-section" aria-label="Catalogue des ressources">
<form method="get" action="<?php echo e(route('resources')); ?>" class="resource-filters"><div><label for="q"><?php echo e(copy_text('resources', 'text_c89223fbd6', 'Rechercher un document')); ?></label><input id="q" name="q" type="search" maxlength="200" value="<?php echo e(request('q')); ?>" placeholder="Titre, sujet…"></div><div><label for="category"><?php echo e(copy_text('resources', 'text_6b38300a25', 'Catégorie')); ?></label><select id="category" name="category"><option value=""><?php echo e(copy_text('resources', 'text_ac8ab261bb', 'Toutes les catégories')); ?></option><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category); ?>" <?php if(request('category') === $category): echo 'selected'; endif; ?>><?php echo e($category); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><button class="button" type="submit"><?php echo e(copy_text('resources', 'text_91f7d3e9dc', 'Rechercher')); ?></button><?php if(request('q') || request('category')): ?><a href="<?php echo e(route('resources')); ?>"><?php echo e(copy_text('resources', 'text_e0e2ad54c1', 'Réinitialiser')); ?></a><?php endif; ?></form>
<div class="activities-heading"><h2><?php echo e(copy_text('resources', 'text_dd61321f42', 'Nos publications')); ?></h2><span><?php echo e($resources->total()); ?> <?php echo e($resources->total() > 1 ? 'ressources' : 'ressource'); ?></span></div>
<div class="activities-grid">
<?php $__empty_1 = true; $__currentLoopData = $resources; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $resource): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><article class="ngo-activity-card"><a class="activity-cover" href="<?php echo e(route('resources.show', $resource->slug)); ?>" aria-label="Lire : <?php echo e($resource->title); ?>"><?php if($resource->cover?->publicUrl()): ?><img src="<?php echo e($resource->cover->publicUrl()); ?>" alt="<?php echo e($resource->cover->alt ?: $resource->title); ?>" width="720" height="480" loading="lazy"><?php else: ?><div class="activity-placeholder" aria-hidden="true"><?php echo e(copy_text('resources', 'text_14347b9fca', 'ADPDH')); ?><span><?php echo e(copy_text('resources', 'text_f1f4b8bc43', 'Ressources et publications')); ?></span></div><?php endif; ?></a><div class="activity-copy"><p class="eyebrow"><?php echo e($resource->category); ?> · PDF</p><h3><a href="<?php echo e(route('resources.show', $resource->slug)); ?>"><?php echo e($resource->title); ?></a></h3><p><?php echo e(Str::limit($resource->description, 180)); ?></p><a class="text-link" href="<?php echo e(route('resources.show', $resource->slug)); ?>">Lire sur le site →</a><?php if($resource->canDownload()): ?><a class="text-link" href="<?php echo e(route('resources.download', $resource->slug)); ?>">Télécharger le PDF ↓</a><?php else: ?><small><?php echo e(copy_text('resources', 'text_d479b0611c', 'Lecture sur le site uniquement')); ?></small><?php endif; ?></div></article>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="activities-empty"><?php echo e(request('q') || request('category') ? 'Aucune ressource ne correspond à votre recherche.' : 'Nos premières ressources seront disponibles prochainement.'); ?></p><?php endif; ?>
</div><?php echo $__env->make('adpdh.activity-pagination', ['paginator' => $resources], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
</section></div>

