<x-layouts.app>
<div class="d-flex justify-content-between flex-wrap gap-3 mb-4"><h1 class="h3">Devenir partenaire</h1><a class="btn btn-outline-primary" href="{{ route('partnership') }}">Voir la page publique</a></div>@include('cms.work.feedback')
<div class="card card-body mb-4"><h2 class="h5">Raisons et formes de partenariat</h2><p>Ajoutez, modifiez, réordonnez ou masquez les éléments à présenter.</p><a class="btn btn-primary align-self-start mb-3" href="{{ route('admin.cms.partnership.create') }}">Ajouter un élément</a><div class="table-responsive"><table class="table"><thead><tr><th>Ordre</th><th>Titre</th><th>Affichage</th><th>Action</th></tr></thead><tbody>@forelse($reasons as $reason)<tr><td>{{ $reason->sort_order }}</td><th>{{ $reason->title }}</th><td>{{ $reason->is_visible ? 'Visible' : 'Masqué' }}</td><td><a href="{{ route('admin.cms.partnership.edit', $reason) }}">Modifier</a></td></tr>@empty<tr><td colspan="4">Aucun élément.</td></tr>@endforelse</tbody></table></div></div>
<section class="card card-body mb-4"><h2 class="h5">Présentation PDF</h2><p>Le remplacement met immédiatement à jour le téléchargement public, sans changer le lien.</p>
@if($pdfAvailable)<p><a href="{{ route('partnership.download') }}">Télécharger le PDF actuel</a></p>@else<p>Aucun document disponible au téléchargement.</p>@endif
<form method="post" enctype="multipart/form-data" action="{{ route('admin.cms.partnership.document') }}">@csrf<label for="pdf" class="form-label">{{ $pdfAvailable ? 'Remplacer le PDF' : 'Ajouter le PDF' }}</label><input type="file" class="form-control mb-2" id="pdf" name="pdf" accept="application/pdf,.pdf" required><p class="small text-muted">PDF uniquement, 20 Mo maximum. Après une erreur, sélectionnez de nouveau le fichier.</p><button class="btn btn-primary">Enregistrer le PDF</button></form>
@if($pdfAvailable)<form method="post" action="{{ route('admin.cms.partnership.document.remove') }}" class="mt-3">@csrf @method('DELETE')<button class="btn btn-outline-danger">Retirer le PDF du site</button></form>@endif</section>
@if($page)<a class="btn btn-outline-primary mb-3" href="{{ route('admin.cms.titles.edit', $page) }}">Personnaliser les titres</a>@endif
<form method="post" action="{{ route('admin.cms.partnership.presentation') }}" class="card card-body">@csrf @method('PUT')<h2 class="h5">Textes et contact partenariat</h2>
@foreach(['introduction'=>'Introduction de la page', 'contact_text'=>'Invitation à prendre contact', 'document_text'=>'Description du document', 'donation_text'=>'Texte du bloc Faire un don'] as $key => $label)<label class="form-label" for="{{ $key }}">{{ $label }}</label><textarea class="form-control mb-3" name="{{ $key }}" id="{{ $key }}" maxlength="2000" rows="3" required>{{ old($key, $copy[$key]) }}</textarea>@endforeach
<label for="email" class="form-label">Email partenariat</label><input class="form-control mb-3" type="email" name="email" id="email" value="{{ old('email', $settings['adpdh.partnership.email'] ?? $settings['adpdh.contact.email'] ?? 'contact@adpdh.org') }}" required>
<label for="phone" class="form-label">Téléphone partenariat</label><input class="form-control mb-3" name="phone" id="phone" value="{{ old('phone', $settings['adpdh.partnership.phone'] ?? $settings['adpdh.contact.phone'] ?? '') }}"><button class="btn btn-primary align-self-start">Enregistrer les textes</button></form>
</x-layouts.app>
