<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{{ $titles['text-2'] }}">
  <meta name="theme-color" content="#17385f">
  <title>{{ $titles['text-1'] }}</title>
  <link rel="icon" href="/adpdh/assets/favicon.png">
  <link rel="stylesheet" href="/adpdh/assets/adpdh.css">
  <link rel="stylesheet" href="/adpdh/assets/refinements.css">
  <link rel="stylesheet" href="/adpdh/assets/pages.css?v=13">
  <script src="/adpdh/assets/adpdh.js?v=11" defer></script>
</head>
<body>
<a class="skip" href="#contenu">Aller au contenu</a>
<div class="topbar"><div class="container"><span>Bukavu, Sud-Kivu · République démocratique du Congo</span><a href="tel:+243896263558">+243 896 263 558 <span aria-hidden="true">↗</span></a></div></div>
<header class="header">
  <div class="container navigation">
    <a class="brand" href="{{ route('admin.cms.preview', $previewPages['index']) }}" aria-label="ADPDH, accueil"><img src="/adpdh/assets/logo-small.webp" width="72" height="72" alt=""><span><strong>ADPDH<span class="brand-dot">.</span></strong><small>Développement & droits humains</small></span></a>
    <button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button>
    <nav id="main-nav" aria-label="Navigation principale">
      <details class="nav-more organization-menu"><summary>Qui sommes-nous ?</summary><div><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Présentation de l’organisation</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#histoire">Notre histoire</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#vision-mission">Vision et mission</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#valeurs">Nos valeurs</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#statut">Statut juridique</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#zones">Zones d’intervention</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#equipe">Notre équipe</a></div></details>
      <a href="{{ route('admin.cms.preview', $previewPages['que-faisons-nous']) }}">Que faisons-nous ?</a>
      <a href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Activités</a>
      <a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Nos succès</a>
      <a href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Notre impact</a>
      <a href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire</a>
      <a href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Contact</a>
      <a class="button button-small button-green" href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don <span aria-hidden="true">↗</span></a>
    </nav>
  </div>
</header>

<main id="contenu">
<section class="photo-hero">
  <div class="hero-background"><img class="" src="/adpdh/assets/community-1200.webp" srcset="/adpdh/assets/community-640.webp 640w, /adpdh/assets/community-1200.webp 1200w, /adpdh/assets/community-1680.webp 1680w" sizes="(max-width: 640px) 100vw, 75vw" width="1680" height="945" alt="Illustration : des adultes échangent autour de cahiers dans un espace communautaire" fetchpriority="high" decoding="async"></div>
  <div class="container photo-hero-copy"><p class="eyebrow">{{ $titles['text-38'] }}</p><h1>{{ $titles['text-3'] }}<br>{{ $titles['text-4'] }}<br><em>{{ $titles['text-5'] }}</em></h1><p>La dignité humaine au cœur de chaque action.<br>Nous accompagnons les communautés vers un avenir plus solidaire, résilient et juste.</p><div class="hero-buttons"><a class="button button-green" href="#piliers">Découvrir notre action <span aria-hidden="true">↗</span></a><a class="text-link light" href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Qui sommes-nous ? <span aria-hidden="true">→</span></a></div></div>
  <div class="container photo-credit">Image d’illustration générée par IA · ne représente pas une activité réelle d’ADPDH</div>
</section>
<section class="stats container" aria-label="Chiffres clés documentés"><div><strong>1 400</strong><span>Bénéficiaires THIMO / STEP</span><small>Projet 2024</small></div><div><strong>3</strong><span>AVEC créées</span><small>Épargne et crédit communautaires</small></div><div><strong>120</strong><span>Membres actifs des AVEC</span><small>Des solidarités qui se construisent</small></div><div><strong>90 <b>%</b></strong><span>Remboursement des crédits</span><small>Au sein des AVEC accompagnées</small></div></section>
<section class="section container home-intro" id="organisation"><div><p class="eyebrow">{{ $titles['text-39'] }}</p><h2>{{ $titles['text-6'] }}<br><em>{{ $titles['text-7'] }}</em></h2></div><div><p class="lead">Les solidarités locales sont le point de départ de notre engagement.</p><p>Créée en 2010, ADPDH contribue à l’autonomisation des populations vulnérables, à la protection de leurs droits et à leur résilience durable dans la région des Grands Lacs.</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Découvrir notre organisation <span aria-hidden="true">→</span></a></div></section>
<section class="section container" id="piliers"><div class="section-heading"><div><p class="eyebrow">{{ $titles['text-40'] }}</p><h2>{{ $titles['text-8'] }}<br><em>{{ $titles['text-9'] }}</em></h2></div><p>Des actions complémentaires, reliées par un principe : placer la dignité humaine au centre de chaque intervention.</p></div><div class="pillar-grid">
    <article class="pillar"><span class="pillar-number">01 <span aria-hidden="true">↗</span></span><h3>{{ $titles['text-10'] }}</h3><p>Renforcer les capacités, l’éducation et les initiatives économiques locales pour une autonomie durable.</p><a href="#activites">Explorer nos activités <span aria-hidden="true">→</span></a></article>
    <article class="pillar"><span class="pillar-number">02 <span aria-hidden="true">↗</span></span><h3>{{ $titles['text-11'] }}</h3><p>Protéger les populations vulnérables, répondre aux urgences et accompagner les personnes affectées par les violences.</p><details><summary>Nos axes d’action</summary><p>Aide humanitaire et protection ; lutte contre les violences basées sur le genre, protection femme-enfant, santé mentale et soutien psychosocial.</p></details></article>
    <article class="pillar"><span class="pillar-number">03 <span aria-hidden="true">↗</span></span><h3>{{ $titles['text-12'] }}</h3><p>Porter la voix des communautés, favoriser le dialogue et préserver les ressources partagées.</p><details><summary>Nos axes d’action</summary><p>Plaidoyer, alerte et consolidation de la paix ; préservation de l’environnement et accès à l’eau, l’hygiène et l’assainissement.</p></details></article>
    <article class="pillar"><span class="pillar-number">04 <span aria-hidden="true">↗</span></span><h3>{{ $titles['text-13'] }}</h3><p>Promouvoir le respect des droits des personnes détenues et faciliter leur réinsertion sociale et économique.</p><details><summary>Notre axe d’action</summary><p>Accès à la justice et réinsertion des personnes détenues, dans le respect de leur dignité.</p></details></article>
  </div></section>
<section class="activities-section" id="activites"><div class="container"><div class="section-heading"><div><p class="eyebrow">{{ $titles['text-41'] }}</p><h2>{{ $titles['text-14'] }}<br><em>{{ $titles['text-15'] }}</em></h2></div><p>Épargne, leadership et réintégration économique : trois formes concrètes de notre engagement.</p></div><div class="activity-showcase"><article class="featured-action"><figure class="editorial-photo "><img class="" src="/adpdh/assets/workshop-1200.webp" srcset="/adpdh/assets/workshop-640.webp 640w, /adpdh/assets/workshop-1200.webp 1200w, /adpdh/assets/workshop-1680.webp 1680w" sizes="(max-width: 640px) 100vw, 75vw" width="1680" height="1260" alt="Illustration : des entrepreneures dans un atelier de couture" loading="lazy" decoding="async"><figcaption>Image d’illustration générée par IA · à remplacer</figcaption></figure><div class="action-copy"><span class="tag">EN COURS · SUD-KIVU</span><h3>{{ $titles['text-16'] }}<br>{{ $titles['text-17'] }}</h3><p>Création et maturation des AVEC, formation à la gestion des activités génératrices de revenus et accompagnement des femmes et des jeunes entrepreneurs.</p><details><summary>AVEC & AGR : notre démarche</summary><p>Instruction de base en français, swahili et mashi, formation à la gouvernance et à l’épargne, puis accompagnement des entreprises.</p></details><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['activite-avec-agr']) }}">Découvrir l’activité →</a></div></article><div class="action-side"><article><span class="action-numeral">02</span><span class="tag">EN COURS</span><h3>{{ $titles['text-18'] }}</h3><p>Des formations et des espaces de dialogue qui renforcent l’autonomisation et la cohésion sociale au Sud-Kivu.</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['activite-resilience']) }}">Découvrir l’activité →</a></article><article><span class="action-numeral">03</span><span class="tag tag-muted">ACHEVÉ · 2023–2024</span><h3>{{ $titles['text-19'] }}</h3><p>ADPDH, partenaire facilitateur de travaux à haute intensité de main-d’œuvre à Kamituga, Bukavu et Uvira.</p><details><summary>Le cadre du projet</summary><p>Projet financé par la Banque mondiale via STEP, sous tutelle du Ministère des Finances (CSPP). Sites : Kamituga ; Mulambula et Kanoshi à Bagira ; Mulongwe et Kasenga à Uvira.</p></details><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['activite-thimo-step']) }}">Découvrir l’activité →</a></article></div></div></div></section>
<section class="impact-section" id="impact"><div class="container impact-grid"><div><p class="eyebrow">{{ $titles['text-42'] }}</p><h2>{{ $titles['text-20'] }}<br><em>{{ $titles['text-21'] }}</em></h2><p>Au-delà de la formation, nous suivons la mise en pratique des acquis et la continuité des activités économiques.</p><p class="source-note">Source : indicateurs communiqués par ADPDH. Les indicateurs AVEC et AGR ne comportent pas encore de date de référence.</p><a class="text-link light" href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Consulter les indicateurs et leurs sources →</a></div><div class="impact-metrics"><div><strong>113</strong><p>Membres formés appliquent la séparation entre la caisse de leur activité et celle du ménage.</p></div><div><strong>56</strong><p>Activités génératrices de revenus toujours actives six mois après la formation.</p></div></div></div></section>
<section class="section container story-preview" id="temoignages"><div><p class="eyebrow">{{ $titles['text-43'] }}</p><h2>{{ $titles['text-22'] }}<br><em>{{ $titles['text-23'] }}</em></h2><p>Les premiers témoignages réels sont en cours de collecte. Cet exemple présente le futur format des récits.</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Découvrir les témoignages →</a></div><figure class="quote-card"><span class="demo-label">Témoignage fictif — à remplacer</span><blockquote>« Je distingue mieux les besoins de mon activité de ceux de mon foyer. Cette organisation m’aide à préparer les prochaines étapes. »</blockquote><figcaption>Personnage de démonstration · aucun bénéficiaire réel représenté</figcaption></figure></section>
<section class="partner-section" id="partenariat"><div class="container"><div class="section-heading"><div><p class="eyebrow">{{ $titles['text-44'] }}</p><h2>{{ $titles['text-24'] }}<br>{{ $titles['text-25'] }} <em>{{ $titles['text-26'] }}</em></h2></div><p>Institutions, bailleurs, organisations et partenaires techniques : construisons des collaborations au service des communautés.</p></div><div class="partnership-types"><span>Financement de projets</span><span>Expertise & appui technique</span><span>Équipements & appui en nature</span><span>Partenariat institutionnel</span></div><a class="button" href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Échanger sur un partenariat <span aria-hidden="true">↗</span></a></div></section>
<section class="section container" id="actualites"><div class="section-heading"><div><p class="eyebrow">{{ $titles['text-45'] }}</p><h2>{{ $titles['text-27'] }} <em>{{ $titles['text-28'] }}</em></h2></div><p>Contenus de démonstration en attendant les premières publications validées par ADPDH.</p></div><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['actualites']) }}">Toutes les actualités →</a><div class="news-preview-grid"><article class="news-preview"><figure class="editorial-photo "><img class="" src="/adpdh/assets/workshop-1200.webp" srcset="/adpdh/assets/workshop-640.webp 640w, /adpdh/assets/workshop-1200.webp 1200w, /adpdh/assets/workshop-1680.webp 1680w" sizes="(max-width: 640px) 100vw, 75vw" width="1680" height="1260" alt="Scène fictive de coopération et d’apprentissage" loading="lazy" decoding="async"><figcaption>Image d’illustration générée par IA · à remplacer</figcaption></figure><div class="news-copy"><span class="demo-label">Exemple fictif — à remplacer</span><p class="eyebrow">{{ $titles['text-46'] }}</p><h3>{{ $titles['text-29'] }}</h3><p>des exercices pratiques permettent de découvrir la tenue d’une caisse et la distinction entre dépenses du foyer et dépenses de l’activité.</p><p class="source-note">Date à renseigner</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['actualite']) }}">Lire l’article →</a></div></article>
<article class="news-preview"><figure class="editorial-photo "><img class="" src="/adpdh/assets/community-1200.webp" srcset="/adpdh/assets/community-640.webp 640w, /adpdh/assets/community-1200.webp 1200w, /adpdh/assets/community-1680.webp 1680w" sizes="(max-width: 640px) 100vw, 75vw" width="1680" height="945" alt="Scène fictive de coopération et d’apprentissage" loading="lazy" decoding="async"><figcaption>Image d’illustration générée par IA · à remplacer</figcaption></figure><div class="news-copy"><span class="demo-label">Exemple fictif — à remplacer</span><p class="eyebrow">{{ $titles['text-47'] }}</p><h3>{{ $titles['text-30'] }}</h3><p>une rencontre de groupe autour des objectifs d’épargne, des règles communes et de la participation de chaque membre.</p><p class="source-note">Date à renseigner</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['actualite-cycle-avec']) }}">Lire l’article →</a></div></article></div></section>
<section class="container compact-resources" id="ressources"><div><p class="eyebrow">{{ $titles['text-48'] }}</p><h3>{{ $titles['text-31'] }}</h3></div><p>Présentation institutionnelle, plan stratégique et rapports : les documents seront accessibles dès leur mise à disposition.</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['ressources']) }}">Voir les ressources <span aria-hidden="true">→</span></a></section>
<section class="donate container" id="soutenir"><div><p class="eyebrow">{{ $titles['text-49'] }}</p><h2>{{ $titles['text-32'] }}<br><em>{{ $titles['text-33'] }}</em></h2></div><div><p>Contribuez aux actions menées auprès des communautés que nous accompagnons.</p><a class="button button-green" href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don <span aria-hidden="true">↗</span></a></div></section>
<section class="section container contact" id="contact"><div><p class="eyebrow">{{ $titles['text-50'] }}</p><h2>{{ $titles['text-34'] }}<br><em>{{ $titles['text-35'] }}</em></h2></div><div><h3>{{ $titles['text-36'] }}</h3><p>305, avenue Patrice Emery Lumumba<br>Commune d’Ibanda, Bukavu<br>Sud-Kivu, République démocratique du Congo</p></div><div><h3>{{ $titles['text-37'] }}</h3><a href="tel:+243896263558">+243 896 263 558</a><a href="mailto:contact@adpdh.org">contact@adpdh.org <span aria-hidden="true">↗</span></a><small>Pour une question, une information ou un premier échange.</small><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Accéder au formulaire →</a></div></section>

</main>
<footer><div class="container footer-grid"><div><a class="footer-brand" href="{{ route('admin.cms.preview', $previewPages['index']) }}">ADPDH<span>.</span></a><p>Action pour le Développement et la Promotion des Droits Humains.</p><span>Bukavu · République démocratique du Congo</span></div><div><h3>L’organisation</h3><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Qui sommes-nous ?</a><a href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Notre impact</a><a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Succès & témoignages</a></div><div><h3>Notre engagement</h3><a href="{{ route('admin.cms.preview', $previewPages['que-faisons-nous']) }}">Nos quatre piliers</a><a href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Nos activités</a><a href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire</a><a href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don</a></div><div><h3>S’informer</h3><a href="{{ route('admin.cms.preview', $previewPages['actualites']) }}">Actualités</a><a href="{{ route('admin.cms.preview', $previewPages['ressources']) }}">Ressources</a><a href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Contact</a><a href="{{ route('admin.cms.preview', $previewPages['mentions-legales']) }}">Mentions légales</a></div></div><div class="container footer-bottom"><span>© <span id="year">2026</span> ADPDH. Tous droits réservés.</span><span>La dignité humaine au centre de chaque intervention.</span><a href="#contenu">Retour en haut ↑</a></div></footer>
<dialog id="donation-dialog" aria-labelledby="donation-title"><button class="dialog-close" data-close aria-label="Fermer">×</button><p class="eyebrow">SOUTENIR ADPDH</p><h2 id="donation-title">Votre solidarité <em>fait la différence.</em></h2><p>Contactez notre équipe pour connaître les modalités de don par virement et confirmer les coordonnées bancaires avant votre contribution.</p><a class="button" href="mailto:contact@adpdh.org?subject=Soutenir%20ADPDH%20par%20un%20don">Demander les modalités <span aria-hidden="true">↗</span></a><p><a href="tel:+243896263558">+243 896 263 558</a></p></dialog>
<dialog id="legal-dialog" aria-labelledby="legal-title"><button class="dialog-close" data-close aria-label="Fermer">×</button><p class="eyebrow">INFORMATIONS</p><h2 id="legal-title">Mentions légales</h2><p>Action pour le Développement et la Promotion des Droits Humains (ADPDH), association sans but lucratif et apolitique créée le 10 janvier 2010 à Bukavu.</p><p>Siège : 305, avenue Patrice Emery Lumumba, commune d’Ibanda, Bukavu, RDC.</p><p>Les mentions complètes, les crédits et les informations relatives à la confidentialité sont en cours de préparation.</p></dialog>

</body>
</html>