<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{{ $titles['text-2'] }}">
  <meta name="theme-color" content="#17385f">
  <title>{{ $titles['text-1'] }}</title>
  <link rel="icon" href="/adpdh/assets/favicon.png">
  <link rel="stylesheet" href="/adpdh/assets/adpdh.css">
  <link rel="stylesheet" href="/adpdh/assets/refinements.css">
  <link rel="stylesheet" href="/adpdh/assets/pages.css?v=13">
  <script src="/adpdh/assets/adpdh.js?v=11" defer></script>
</head>
<body>
<a class="skip" href="#contenu">Aller au contenu</a>
<div class="topbar"><div class="container"><span>Bukavu, Sud-Kivu · République démocratique du Congo</span><a href="tel:+243896263558">+243 896 263 558 <span aria-hidden="true">↗</span></a></div></div>
<header class="header">
  <div class="container navigation">
    <a class="brand" href="{{ route('admin.cms.preview', $previewPages['index']) }}" aria-label="ADPDH, accueil"><img src="/adpdh/assets/logo-small.webp" width="72" height="72" alt=""><span><strong>ADPDH<span class="brand-dot">.</span></strong><small>Développement & droits humains</small></span></a>
    <button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button>
    <nav id="main-nav" aria-label="Navigation principale">
      <details class="nav-more organization-menu"><summary>Qui sommes-nous ?</summary><div><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}" aria-current="page">Présentation de l’organisation</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#histoire">Notre histoire</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#vision-mission">Vision et mission</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#valeurs">Nos valeurs</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#statut">Statut juridique</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#zones">Zones d’intervention</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#equipe">Notre équipe</a></div></details>
      <a href="{{ route('admin.cms.preview', $previewPages['que-faisons-nous']) }}">Que faisons-nous ?</a>
      <a href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Activités</a>
      <a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Nos succès</a>
      <a href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Notre impact</a>
      <a href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire</a>
      <a href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Contact</a>
      <a class="button button-small button-green" href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don <span aria-hidden="true">↗</span></a>
    </nav>
  </div>
</header>

<main id="contenu">
<div class="container breadcrumb" aria-label="Fil d’Ariane"><a href="{{ route('admin.cms.preview', $previewPages['index']) }}">Accueil</a><span aria-hidden="true">/</span><span>Qui sommes-nous ?</span></div>
<section class="container about-heading"><p class="eyebrow">{{ $titles['text-36'] }}</p><h1>{{ $titles['text-3'] }}<br><em>{{ $titles['text-4'] }}</em></h1><p>Action pour le Développement et la Promotion des Droits Humains.<br>Une organisation née à Bukavu, guidée par la dignité humaine.</p></section>
<div class="container about-cover"><figure class="editorial-photo "><img class="" src="/adpdh/assets/community-1200.webp" srcset="/adpdh/assets/community-640.webp 640w, /adpdh/assets/community-1200.webp 1200w, /adpdh/assets/community-1680.webp 1680w" sizes="(max-width: 640px) 100vw, 75vw" width="1680" height="945" alt="Illustration : un groupe échange et travaille ensemble" loading="lazy" decoding="async"><figcaption>Image d’illustration générée par IA · à remplacer</figcaption></figure><div class="cover-note"><strong>Depuis 2010</strong><span>Développement · Protection · Droits humains</span></div></div>
<nav class="page-subnav" aria-label="Sur cette page"><div class="container"><a href="#histoire">Notre histoire</a><a href="#vision-mission">Vision & mission</a><a href="#valeurs">Nos valeurs</a><a href="#statut">Statut juridique</a><a href="#zones">Zones d’intervention</a><a href="#equipe">Notre équipe</a></div></nav>
<section class="section container history-layout" id="histoire"><div><p class="eyebrow">{{ $titles['text-37'] }}</p><h2>{{ $titles['text-5'] }}<br>{{ $titles['text-6'] }} <em>{{ $titles['text-7'] }}</em></h2><p class="history-aside">Construire des ponts entre les communautés et faire grandir les solidarités qui existent déjà.</p></div><div><p class="lead">L’histoire d’ADPDH commence par une conviction partagée par deux jeunes de Bukavu : le développement doit partir des forces des communautés.</p><p>Daniel Uwezo et Docile Utashi grandissent dans une région marquée par les conflits. Ils s’interrogent sur ce qui manque pour bâtir une paix durable : une cohésion sociale réelle et des initiatives qui placent l’être humain au centre.</p><p>Leur engagement civique, puis leurs rencontres avec d’autres communautés, renforcent cette intuition. Les mécanismes d’épargne collective, de médiation et de solidarité constituent déjà une base sur laquelle construire.</p><ol class="timeline"><li><span>2006</span><div><h3>{{ $titles['text-8'] }}</h3><p>Au Parlement des Enfants du Sud-Kivu, Daniel et Docile participent à un espace civique qui leur permet de porter la voix de leur génération.</p></div></li><li><span>2010</span><div><h3>{{ $titles['text-9'] }}</h3><p>Le 10 janvier, ils fondent ADPDH à Bukavu avec un cercle d’amis et de connaissances engagés dans la même cause.</p></div></li><li><span>Aujourd’hui</span><div><h3>{{ $titles['text-10'] }}</h3><p>À travers les AVEC, l’accompagnement des initiatives économiques et le travail de cohésion sociale, ADPDH soutient une autonomie qui se construit depuis les communautés.</p></div></li></ol><details class="story"><summary>Le contexte qui a nourri cet engagement <span aria-hidden="true">+</span></summary><p>Le récit fondateur situe cet engagement dans l’histoire de Bukavu, marquée par les bouleversements de 1996, la rébellion de 1998 et les violences de 2004. Ces expériences nourrissent chez les fondateurs une réflexion sur les liens entre cohésion sociale, richesse culturelle et développement.</p><p>Les voyages et les rencontres qui suivent leur montrent des communautés capables de s’appuyer sur leurs propres pratiques de solidarité. ADPDH naît de cette volonté de relier les ressources humaines et culturelles de la région, plutôt que de les laisser se fragmenter.</p></details></div></section>
<section class="mission-band" id="vision-mission"><div class="container mission-grid"><article><p class="eyebrow">{{ $titles['text-38'] }}</p><h2>{{ $titles['text-11'] }}<br>{{ $titles['text-12'] }} <em>{{ $titles['text-13'] }}</em></h2><p>Une région des Grands Lacs où chaque personne, en particulier les plus vulnérables, vit dans la dignité, la paix et la sécurité, et jouit pleinement de ses droits fondamentaux.</p></article><article><p class="eyebrow">{{ $titles['text-39'] }}</p><h2>{{ $titles['text-14'] }}<br><em>{{ $titles['text-15'] }}</em></h2><p>Contribuer à l’autonomisation des populations et communautés vulnérables, à la protection de leurs droits et à leur résilience durable, à travers des actions intégrées de développement, d’urgence humanitaire, de protection et de plaidoyer.</p></article></div></section>
<section class="section container" id="valeurs"><div class="section-heading"><div><p class="eyebrow">{{ $titles['text-40'] }}</p><h2>{{ $titles['text-16'] }}<br><em>{{ $titles['text-17'] }}</em></h2></div><p>Des principes partagés dans nos relations avec les communautés et nos partenaires.</p></div><div class="values-layout"><figure class="editorial-photo "><img class="" src="/adpdh/assets/workshop-1200.webp" srcset="/adpdh/assets/workshop-640.webp 640w, /adpdh/assets/workshop-1200.webp 1200w, /adpdh/assets/workshop-1680.webp 1680w" sizes="(max-width: 640px) 100vw, 75vw" width="1680" height="1260" alt="Illustration : des entrepreneures dans un atelier de couture" loading="lazy" decoding="async"><figcaption>Image d’illustration générée par IA · à remplacer</figcaption></figure><ol class="values-list"><li><span>01</span><div><h3>{{ $titles['text-18'] }}</h3><p>Respect de la dignité et des droits de chaque personne.</p></div></li><li><span>02</span><div><h3>{{ $titles['text-19'] }}</h3><p>Envers les communautés et les partenaires.</p></div></li><li><span>03</span><div><h3>{{ $titles['text-20'] }}</h3><p>Une action humanitaire impartiale et indépendante.</p></div></li><li><span>04</span><div><h3>{{ $titles['text-21'] }}</h3><p>Égalité de genre et participation de toutes et tous.</p></div></li><li><span>05</span><div><h3>{{ $titles['text-22'] }}</h3><p>Des principes au cœur de l’action collective.</p></div></li></ol></div></section>
<section class="institutional-section" id="statut"><div class="container institutional-grid"><div><p class="eyebrow">{{ $titles['text-41'] }}</p><h2>{{ $titles['text-23'] }}<br><em>{{ $titles['text-24'] }}</em></h2></div><dl class="identity-facts"><div><dt>Dénomination</dt><dd>Action pour le Développement et la Promotion des Droits Humains — ADPDH</dd></div><div><dt>Statut</dt><dd>Association sans but lucratif, apolitique, de développement communautaire et des droits humains</dd></div><div><dt>Création</dt><dd>10 janvier 2010, à Bukavu</dd></div><div><dt>Siège</dt><dd>305, avenue Patrice Emery Lumumba, commune d’Ibanda, Bukavu, RDC</dd></div></dl></div></section>
<section class="section container geography" id="zones"><div><p class="eyebrow">{{ $titles['text-42'] }}</p><h2>{{ $titles['text-25'] }}<br><em>{{ $titles['text-26'] }}</em></h2><p class="lead">ADPDH intervient dans la région des Grands Lacs, principalement au Nord-Kivu et au Sud-Kivu.</p><p>L’organisation porte une ambition régionale et internationale. Son développement géographique reste lié à ses capacités et aux financements disponibles.</p><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Découvrir les activités <span aria-hidden="true">→</span></a></div><div class="territory-panel"><p class="eyebrow">{{ $titles['text-43'] }}</p><div class="territory-row"><span class="dot"></span><div><h3>{{ $titles['text-27'] }}</h3><p>Bukavu, siège de l’organisation<br>Kamituga, Bukavu et Uvira : sites du projet STEP</p></div></div><div class="territory-row"><span class="dot"></span><div><h3>{{ $titles['text-28'] }}</h3><p>Province d’intervention mentionnée dans le document institutionnel.</p></div></div><details><summary>Perspectives d’extension</summary><p>Tanganyika, Ituri, Haut-Uele, Maniema, Kasaï et Lualaba. Ces extensions sont envisagées ; elles ne sont pas présentées comme des implantations actuelles.</p></details></div></section>
<section class="section container" id="equipe"><p class="eyebrow">{{ $titles['text-44'] }}</p><h2>{{ $titles['text-29'] }}</h2><div class="team-grid"><article><div class="team-avatar"><img src="/adpdh/assets/avatar-default.svg" alt="" width="480" height="480" loading="lazy" decoding="async" data-team-photo></div><h3>{{ $titles['text-30'] }}</h3><p>Coordonnateur</p><details class="team-contact"><summary>Coordonnées</summary><div class="team-contact-links"><a href="tel:+243812438762">+243 812 438 762</a><a href="mailto:danieluwezo@adpdh.org">danieluwezo@adpdh.org</a></div></details></article><article><div class="team-avatar"><img src="/adpdh/assets/avatar-default.svg" alt="" width="480" height="480" loading="lazy" decoding="async" data-team-photo></div><h3>{{ $titles['text-31'] }}</h3><p>Chargée de programmes</p><details class="team-contact"><summary>Coordonnées</summary><div class="team-contact-links"><a href="tel:+243897440440">+243 897 440 440</a><a href="mailto:solangemulinganya@adpdh.org">solangemulinganya@adpdh.org</a></div></details></article><article><div class="team-avatar"><img src="/adpdh/assets/avatar-default.svg" alt="" width="480" height="480" loading="lazy" decoding="async" data-team-photo></div><h3>{{ $titles['text-32'] }}</h3><p>Animateur social</p><details class="team-contact"><summary>Coordonnées</summary><div class="team-contact-links"><a href="tel:+243977720122">+243 977 720 122</a><span>E-mail non renseigné</span></div></details></article><article><div class="team-avatar"><img src="/adpdh/assets/avatar-default.svg" alt="" width="480" height="480" loading="lazy" decoding="async" data-team-photo></div><h3>{{ $titles['text-33'] }}</h3><p>Animatrice sociale et formatrice</p><details class="team-contact"><summary>Coordonnées</summary><div class="team-contact-links"><a href="tel:+243906188784">+243 906 188 784</a><span>E-mail non renseigné</span></div></details></article></div></section>

<section class="container about-cta"><div><p class="eyebrow">{{ $titles['text-45'] }}</p><h2>{{ $titles['text-34'] }}<br><em>{{ $titles['text-35'] }}</em></h2></div><a class="button button-green" href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire <span aria-hidden="true">↗</span></a></section>

</main>
<footer><div class="container footer-grid"><div><a class="footer-brand" href="{{ route('admin.cms.preview', $previewPages['index']) }}">ADPDH<span>.</span></a><p>Action pour le Développement et la Promotion des Droits Humains.</p><span>Bukavu · République démocratique du Congo</span></div><div><h3>L’organisation</h3><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Qui sommes-nous ?</a><a href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Notre impact</a><a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Succès & témoignages</a></div><div><h3>Notre engagement</h3><a href="{{ route('admin.cms.preview', $previewPages['que-faisons-nous']) }}">Nos quatre piliers</a><a href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Nos activités</a><a href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire</a><a href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don</a></div><div><h3>S’informer</h3><a href="{{ route('admin.cms.preview', $previewPages['actualites']) }}">Actualités</a><a href="{{ route('admin.cms.preview', $previewPages['ressources']) }}">Ressources</a><a href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Contact</a><a href="{{ route('admin.cms.preview', $previewPages['mentions-legales']) }}">Mentions légales</a></div></div><div class="container footer-bottom"><span>© <span id="year">2026</span> ADPDH. Tous droits réservés.</span><span>La dignité humaine au centre de chaque intervention.</span><a href="#contenu">Retour en haut ↑</a></div></footer>
<dialog id="donation-dialog" aria-labelledby="donation-title"><button class="dialog-close" data-close aria-label="Fermer">×</button><p class="eyebrow">SOUTENIR ADPDH</p><h2 id="donation-title">Votre solidarité <em>fait la différence.</em></h2><p>Contactez notre équipe pour connaître les modalités de don par virement et confirmer les coordonnées bancaires avant votre contribution.</p><a class="button" href="mailto:contact@adpdh.org?subject=Soutenir%20ADPDH%20par%20un%20don">Demander les modalités <span aria-hidden="true">↗</span></a><p><a href="tel:+243896263558">+243 896 263 558</a></p></dialog>
<dialog id="legal-dialog" aria-labelledby="legal-title"><button class="dialog-close" data-close aria-label="Fermer">×</button><p class="eyebrow">INFORMATIONS</p><h2 id="legal-title">Mentions légales</h2><p>Action pour le Développement et la Promotion des Droits Humains (ADPDH), association sans but lucratif et apolitique créée le 10 janvier 2010 à Bukavu.</p><p>Siège : 305, avenue Patrice Emery Lumumba, commune d’Ibanda, Bukavu, RDC.</p><p>Les mentions complètes, les crédits et les informations relatives à la confidentialité sont en cours de préparation.</p></dialog>

</body>
</html>