<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex, nofollow">
  <meta name="description" content="{{ $titles['text-2'] }}">
  <meta name="theme-color" content="#17385f">
  <title>{{ $titles['text-1'] }}</title>
  <link rel="icon" href="/adpdh/assets/favicon.png">
  <link rel="stylesheet" href="/adpdh/assets/adpdh.css">
  <link rel="stylesheet" href="/adpdh/assets/refinements.css">
  <link rel="stylesheet" href="/adpdh/assets/pages.css?v=13">
  <script src="/adpdh/assets/adpdh.js?v=11" defer></script>
</head>
<body>
<a class="skip" href="#contenu">Aller au contenu</a>
<div class="topbar"><div class="container"><span>Bukavu, Sud-Kivu · République démocratique du Congo</span><a href="tel:+243896263558">+243 896 263 558 <span aria-hidden="true">↗</span></a></div></div>
<header class="header">
  <div class="container navigation">
    <a class="brand" href="{{ route('admin.cms.preview', $previewPages['index']) }}" aria-label="ADPDH, accueil"><img src="/adpdh/assets/logo-small.webp" width="72" height="72" alt=""><span><strong>ADPDH<span class="brand-dot">.</span></strong><small>Développement & droits humains</small></span></a>
    <button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu <span aria-hidden="true">☰</span></button>
    <nav id="main-nav" aria-label="Navigation principale">
      <details class="nav-more organization-menu"><summary>Qui sommes-nous ?</summary><div><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Présentation de l’organisation</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#histoire">Notre histoire</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#vision-mission">Vision et mission</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#valeurs">Nos valeurs</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#statut">Statut juridique</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#zones">Zones d’intervention</a><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}#equipe">Notre équipe</a></div></details>
      <a href="{{ route('admin.cms.preview', $previewPages['que-faisons-nous']) }}">Que faisons-nous ?</a>
      <a href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Activités</a>
      <a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}" aria-current="true">Nos succès</a>
      <a href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Notre impact</a>
      <a href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire</a>
      <a href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Contact</a>
      <a class="button button-small button-green" href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don <span aria-hidden="true">↗</span></a>
    </nav>
  </div>
</header>

<main id="contenu">
<div class="container breadcrumb" aria-label="Fil d’Ariane"><a href="{{ route('admin.cms.preview', $previewPages['index']) }}">Accueil</a><span aria-hidden="true">/</span><a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Témoignages</a><span aria-hidden="true">/</span><span>Récit de démonstration</span></div><section class="container about-heading"><p class="eyebrow">{{ $titles['text-9'] }}</p><h1>{{ $titles['text-3'] }}<br><em>{{ $titles['text-4'] }}</em></h1><p>Un exemple de mise en page pour les futurs témoignages AVEC & AGR.</p></section><div class="container collection-notice"><span class="demo-label">Exemple fictif — à remplacer</span><p>Ce récit et cette citation sont fictifs. Ils ne décrivent aucune personne accompagnée par ADPDH et ne constituent pas un résultat de l’organisation.</p></div><article class="section container story-detail"><aside><div class="portrait-placeholder" role="img" aria-label="Emplacement de portrait : aucun bénéficiaire réel représenté"><span aria-hidden="true">ADPDH<span class="portrait-circle"></span></span><p>Portrait à venir<br><small>Aucun bénéficiaire réel représenté</small></p></div><p class="source-note">Personnage de démonstration · portrait non fourni</p></aside><div><p class="eyebrow">{{ $titles['text-10'] }}</p><section><h2>{{ $titles['text-5'] }}</h2><p>Dans cet exemple fictif, une personne qui développe une petite activité utilise la même caisse pour ses achats professionnels et les dépenses de son foyer. Il lui est difficile de savoir ce qui reste disponible pour renouveler ses produits.</p></section><section><h2>{{ $titles['text-6'] }}</h2><p>Le récit imagine l’apprentissage d’une distinction entre dépenses de l’activité et besoins du ménage, puis la mise en place d’un suivi simple des entrées et des sorties.</p><blockquote class="quote-card">« Je distingue mieux les besoins de mon activité de ceux de mon foyer. Cette organisation m’aide à préparer les prochaines étapes. »</blockquote></section><section><h2>{{ $titles['text-7'] }}</h2><p>Dans ce scénario de démonstration, ces repères facilitent la préparation des prochains achats. Aucun revenu, montant épargné ou changement familial réel n’est attribué à cette personne fictive.</p></section></div></article><section class="container story-media"><p class="eyebrow">{{ $titles['text-11'] }}</p><h2>{{ $titles['text-8'] }}</h2><p>Les photographies et vidéos des futurs témoignages seront ajoutées après collecte et autorisation des personnes concernées.</p><div class="media-pending">Aucun média de témoignage disponible pour le moment.</div></section><div class="container activity-back"><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">← Tous les témoignages</a><a class="text-link" href="{{ route('admin.cms.preview', $previewPages['activite-avec-agr']) }}">Comprendre l’activité AVEC & AGR →</a></div>
</main>
<footer><div class="container footer-grid"><div><a class="footer-brand" href="{{ route('admin.cms.preview', $previewPages['index']) }}">ADPDH<span>.</span></a><p>Action pour le Développement et la Promotion des Droits Humains.</p><span>Bukavu · République démocratique du Congo</span></div><div><h3>L’organisation</h3><a href="{{ route('admin.cms.preview', $previewPages['qui-sommes-nous']) }}">Qui sommes-nous ?</a><a href="{{ route('admin.cms.preview', $previewPages['impact']) }}">Notre impact</a><a href="{{ route('admin.cms.preview', $previewPages['temoignages']) }}">Succès & témoignages</a></div><div><h3>Notre engagement</h3><a href="{{ route('admin.cms.preview', $previewPages['que-faisons-nous']) }}">Nos quatre piliers</a><a href="{{ route('admin.cms.preview', $previewPages['activites']) }}">Nos activités</a><a href="{{ route('admin.cms.preview', $previewPages['devenir-partenaire']) }}">Devenir partenaire</a><a href="{{ route('admin.cms.preview', $previewPages['faire-un-don']) }}">Faire un don</a></div><div><h3>S’informer</h3><a href="{{ route('admin.cms.preview', $previewPages['actualites']) }}">Actualités</a><a href="{{ route('admin.cms.preview', $previewPages['ressources']) }}">Ressources</a><a href="{{ route('admin.cms.preview', $previewPages['contact']) }}">Contact</a><a href="{{ route('admin.cms.preview', $previewPages['mentions-legales']) }}">Mentions légales</a></div></div><div class="container footer-bottom"><span>© <span id="year">2026</span> ADPDH. Tous droits réservés.</span><span>La dignité humaine au centre de chaque intervention.</span><a href="#contenu">Retour en haut ↑</a></div></footer>
<dialog id="donation-dialog" aria-labelledby="donation-title"><button class="dialog-close" data-close aria-label="Fermer">×</button><p class="eyebrow">SOUTENIR ADPDH</p><h2 id="donation-title">Votre solidarité <em>fait la différence.</em></h2><p>Contactez notre équipe pour connaître les modalités de don par virement et confirmer les coordonnées bancaires avant votre contribution.</p><a class="button" href="mailto:contact@adpdh.org?subject=Soutenir%20ADPDH%20par%20un%20don">Demander les modalités <span aria-hidden="true">↗</span></a><p><a href="tel:+243896263558">+243 896 263 558</a></p></dialog>
<dialog id="legal-dialog" aria-labelledby="legal-title"><button class="dialog-close" data-close aria-label="Fermer">×</button><p class="eyebrow">INFORMATIONS</p><h2 id="legal-title">Mentions légales</h2><p>Action pour le Développement et la Promotion des Droits Humains (ADPDH), association sans but lucratif et apolitique créée le 10 janvier 2010 à Bukavu.</p><p>Siège : 305, avenue Patrice Emery Lumumba, commune d’Ibanda, Bukavu, RDC.</p><p>Les mentions complètes, les crédits et les informations relatives à la confidentialité sont en cours de préparation.</p></dialog>

</body>
</html>